/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/5Kg6hL4o9Xn
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { DM_Sans } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Slider } from "@/components/ui/slider"
import { Checkbox } from "@/components/ui/checkbox"
import { Input } from "@/components/ui/input"

export function YoutubeSearch() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <YoutubeIcon className="h-6 w-6" />
          <span className="sr-only">My YouTube Channel</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Home
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Videos
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            About
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full pt-12 md:pt-24 lg:pt-32">
          <div className="container space-y-10 xl:space-y-16">
            <div className="grid gap-4 px-4 md:grid-cols-2 md:gap-16">
              <div>
                <span className="mx-auto aspect-video overflow-hidden object-cover rounded-md bg-gray-100 dark:bg-gray-800" />
                <div className="mt-4">
                  <h2 className="font-bold text-xl" />
                  <div className="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
                    <Avatar>
                      <AvatarImage />
                      <AvatarFallback />
                    </Avatar>
                    <span> views</span>
                    <span>·</span>
                    <span />
                    <span>·</span>
                    <span> comments</span>
                  </div>
                  <div className="mt-6">
                    <div className="flex items-center justify-between mb-4">
                      <h3 className="font-semibold">Latest Comments</h3>
                      <Button size="icon" variant="ghost">
                        <CogIcon className="w-4 h-4" />
                      </Button>
                    </div>
                    <div className="flex flex-col gap-4 mb-4">
                      <div className="flex items-center gap-4">
                        <Label htmlFor="commentThreshold">Comment Threshold</Label>
                        <Slider className="flex-1" id="commentThreshold" max={5} min={-5} step={1} value={[0]} />
                        <span className="text-sm text-gray-500 dark:text-gray-400">
                          Only show comments with a score above this threshold
                        </span>
                      </div>
                      <div className="flex items-center gap-4">
                        <Checkbox id="hideRedactedComments">
                          <Label htmlFor="hideRedactedComments">Hide Redacted Comments</Label>
                        </Checkbox>
                        <span className="text-sm text-gray-500 dark:text-gray-400">
                          Hide comments that have been redacted due to low score
                        </span>
                      </div>
                    </div>
                    <div className="grid gap-4" />
                  </div>
                </div>
              </div>
              <div className="flex flex-col items-start space-y-4">
                <h1 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
                  Find your Video
                </h1>
                <form className="w-full max-w-lg">
                  <div className="relative">
                    <Input className="w-full" placeholder="Search for a video" type="text" />
                    <Button className="absolute top-1/2 right-2 -translate-y-1/2" type="submit">
                      <SearchIcon className="h-5 w-5" />
                    </Button>
                    <div className="absolute top-full left-0 w-full bg-white dark:bg-gray-800 rounded-lg shadow-lg mt-2 z-10 max-h-[300px] overflow-y-auto">
                      <ul className="py-2" />
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}

function CogIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 20a8 8 0 1 0 0-16 8 8 0 0 0 0 16Z" />
      <path d="M12 14a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z" />
      <path d="M12 2v2" />
      <path d="M12 22v-2" />
      <path d="m17 20.66-1-1.73" />
      <path d="M11 10.27 7 3.34" />
      <path d="m20.66 17-1.73-1" />
      <path d="m3.34 7 1.73 1" />
      <path d="M14 12h8" />
      <path d="M2 12h2" />
      <path d="m20.66 7-1.73 1" />
      <path d="m3.34 17 1.73-1" />
      <path d="m17 3.34-1 1.73" />
      <path d="m11 13.73-4 6.93" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function YoutubeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17" />
      <path d="m10 15 5-3-5-3z" />
    </svg>
  )
}
